name: Creativerse
version: 1.2.1
author: phaze jeff
main: com.creativerse.Creativerse
api-version: 1.14
depend: [WorldEdit, PlotSquared]
commands:
  save:
    description: Saves your plot of land that you are in onto a file.
    usage: /<command>
  sync:
    description: Syncs the plot you are standing on with version stored on chain.
    usage: /<command>
  link:
    description: Links an Ethereum address with a Minecraft account.
    usage: /<command>
  syncall:
    description: Syncs all plots with the version stored on chain.
    usage: /<command>
    permission: creativerse.syncall
    permission-message: You do not have permission!
  autosync:
    description: Toggles the auto sync on the plot you are standing on with the version stored on chain every time it updates.
    usage: /<command>
  creativerse reload:
    description: Reloads config.
    usage: /<command>
permissions:
  creativerse.syncall:
    description: Allows SyncAll command and allows Sync command on any plot.
    default: op
  creativerse.*:
    description: All Creativerse commands
    default: op
    children:
      creativerse.syncall: true